CREATE USER 'bookstore'@'%' IDENTIFIED VIA mysql_native_password USING 'bookstore';
GRANT USAGE ON *.* TO 'bookstore'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;


GRANT ALL PRIVILEGES ON `bookstore`.* TO `bookstore`@`%` WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `authentication`.* TO `bookstore`@`%` WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `sales`.* TO `bookstore`@`%` WITH GRANT OPTION;
