CREATE TABLE author (
		name VARCHAR(15) PRIMARY KEY
) ENGINE=InnoDB CHARSET=utf8;


CREATE TABLE publisher (
		name VARCHAR(20) PRIMARY KEY,
		address TEXT NOT NULL,
		contact VARCHAR(10) NOT NULL UNIQUE
) ENGINE=InnoDB CHARSET=utf8;


CREATE TABLE series (
		title VARCHAR(30) PRIMARY KEY,
		author VARCHAR(15) NOT NULL,
		publisher VARCHAR(15) NOT NULL,
		total_books INT(2) DEFAULT 0,

		FOREIGN KEY (author) REFERENCES author(name) ON DELETE CASCADE ON UPDATE CASCADE
		FOREIGN KEY (publisher) REFERNCES publisher(name) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARSET=utf8;


CREATE TABLE book (
		isbn INT(13) PRIMARY KEY,
		name VARCHAR(100) NOT NULL UNIQUE,
		price FLOAT NOT NULL,
		book_number INT(2) DEFAULT NULL,
		series VARCHAR(15) DEFAULT NULL,
		publisher VARCHAR(15) NOT NULL,
		author VARCHAR(15) NOT NULL,

		FOREIGN KEY (series) REFERENCES series(title) ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (publisher) REFERENCES publisher(name) ON DELETE CASCADE ON UPDATE CASCADE,
		FOREIGN KEY (author) REFERENCES author(name) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARSET=utf8;
